### ISSUE TITLE
Add logo to site and other branding changes

### ISSUE THREAD

**Issue by anderspeders** [NRGI/nrgi-country-dashboards#21]
![image](https://cloud.githubusercontent.com/assets/1101585/9839269/20bab636-5a42-11e5-9cc8-6565b5341cbb.png)

I think this is the most high res available.

**Comment by markbrough** [comment]
- The home page needs improvement to show clear identity of GHEITI
  - [x] GHEITI logo
  - [x] Map of Ghana
