### ISSUE TITLE
GHEITI vs EITI dataset

### ISSUE THREAD

**Issue by markbrough** [NRGI/nrgi-country-dashboards#3]
There are some differences in the GHEITI and EITI datasets for showing the breakdown by commodity. The GHEITI dataset appears more complete and has fewer discontinuities in the time series. This could be improved further by combining commodities, i.e. all commodities that include "Gold" (see #2).

Here is the breakdown by commodity for the EITI dataset:

| Commodity | 2004 | 2005 | 2006 | 2007 | 2008 | 2009 | 2010 | 2011 | 2012 | 2013 | Grand Total |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Bauxite |  | 431213 | 673443 | 559648 | 450138 | 563882 | 733208 | 489265 |  |  | 3900797 |
| Diamond |  |  |  |  |  |  |  |  |  |  |  |
| Diamonds |  |  |  |  |  |  |  |  |  |  |  |
| Gas |  |  |  |  |  |  |  |  |  |  |  |
| Gold |  | 42823299 | 64400769 | 59949084 | 86750625 | 103065649.3 | 203397829 | 462115969 |  |  | 1022503224 |
| Manganese |  | 1400131 | 1146348 | 1258811 | 3992719 | 8342782 | 8640399 | 35742538 |  |  | 60523728 |
| Oil |  |  |  |  |  |  |  |  |  | 845870483.7 | 845870483.7 |
| Salt |  |  |  |  |  |  |  |  |  |  |  |
| Silver |  |  |  |  |  |  |  |  |  |  |  |

And here's the breakdown by commodity for the GHEITI dataset:

| Commodity | 2007 | 2008 | 2009 | 2010 | 2011 | 2012 | 2013 |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Bauxite | 554052 | 472645 | 592076 | 1033823 | 689863 | 1996845 | 3419198 |
| Gold | 59349593 | 91156795 | 106185568 | 282780745 | 707992746 | 918376207 | 598600648.4 |
| Gold/Diamond |  |  |  |  |  | 101852040 | 144222650.8 |
| Gold/other Base |  |  |  |  |  | 16284814 | 14953065 |
| Gold/Silver |  |  |  |  |  | 39489624 | 28177714.23 |
| Limestone |  |  |  |  |  | 1226624 | 1433653 |
| Manganese | 1246223 | 4123716 | 8759922 | 12182963 | 50396979 | 28905152 | 37134557 |
| Oil |  |  |  | 422252.23 | 356755032.7 | 437301749.4 | 724808288 |
| (blank) |  |  | 1973364 | 2976370 | 3392503 | 5162056 | 0 |

**Comment by markbrough** [comment]
The EITI dataset does actually have an amount for 2012, but the commodity is miscoded (as `Total` rather than `Oil`)

**Comment by anderspeders** [comment]
Could you email samuel and I?

**Comment by markbrough** [comment]
We will use Samuel's dataset instead.
