### ISSUE TITLE
Add source descrip or link to each visualization

### ISSUE THREAD

**Issue by anderspeders** [NRGI/nrgi-country-dashboards#4]
My assumption would be that the best way to inform about the data source would be in the right corner of each visualization. 

Eg.
![source dashboards](https://cloud.githubusercontent.com/assets/1101585/8937401/24ea4ed8-3526-11e5-8748-47810d272910.JPG)

**Comment by markbrough** [comment]
Added a source link under each visualisation. Some may need to be adjusted or lengthened.
