### ISSUE TITLE
Display Cedi vs USD - both or select one

### ISSUE THREAD

**Issue by anderspeders** [NRGI/nrgi-country-dashboards#5]
Generally agreed OK to use either, but need to be consistent.

Ability in front end to convert between the two? Use annualised conversion rate?

**Comment by anderspeders** [comment]
Not sure what we agreed here, 

Maybe worth checking with David and Samuel.

**Comment by markbrough** [comment]
From the notes - we said either would be OK but we need to be consistent. At the moment everything is in USD (though it doesn't say that anywhere). But it might be nice to have the possibility to switch between USD and Cedi. Suggest we take a look at it again once later once some of the other things are done.

**Comment by markbrough** [comment]
Everything is now in Cedi. Suggest revisiting later whether we should make it possible to convert on the fly to USD.
