### ISSUE TITLE
Include spending and deficit in chart with revenues

### ISSUE THREAD

**Issue by anderspeders** [NRGI/nrgi-country-dashboards#6]
This will require a data package of the IMF spending / deficit data: 
https://docs.google.com/spreadsheets/d/17nA4Z0BUx38A7x_Wds7Eo939dLR9Scp-KcxQiPCvNv4/edit#gid=631891038

tbc with Daivd and Giorgia

**Comment by anderspeders** [comment]
Here is the dtaa package which @byndcivilization has used before for this: 

http://data.okfn.org/data/core/imf-weo

**Comment by anderspeders** [comment]
Is this still on the list for add-ons?

**Comment by markbrough** [comment]
Implemented in a39b53fd1307124eaa888e1951f98f9f1cc3218c
