### ISSUE TITLE
Various bug fixes

### ISSUE THREAD

**Issue by anderspeders** [NRGI/nrgi-country-dashboards#8]
generally
breakdown by commodity pie chart

fix time buttons (they work but they don’t change colour when you click on them) or replace with a slider?
add companies for that particular year and total revenue, plus possibly breakdown by commodity for 

each company if that wouldn’t be too confusing for the UI

add legend

line charts
add legend
add pop-up for data point (to tell you exact amount at that data point)

**Comment by markbrough** [comment]
- breakdown by commodity pie chart
  - [x] fix time buttons (they work but they don’t change colour when you click on them) ~~or replace with a slider~~?
  - [x] add companies for that particular year and total revenue
  - [x] plus possibly breakdown by commodity for each company if that wouldn’t be too confusing for the UI
  - [x] add legend
  - [x] fix tooltips
  - [x] fix pie chart animation abruptly terminating when mouse moves away
- line charts
  - [x] add legend
  - [x] add pop-up for data point (to tell you exact amount at that data point)

**Comment by markbrough** [comment]
All fixed, though will consider time slider improvement, logged in #17
